# Generated by Django 4.2.4 on 2023-08-14 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('TD', 'To do'), ('PR', 'In progress'), ('FN', 'Finished')], max_length=2)),
                ('priority', models.CharField(choices=[('LO', 'Low'), ('MD', 'Medium'), ('HI', 'High')], max_length=2)),
                ('tag', models.CharField(choices=[('BUG', 'Bug'), ('TAS', 'Task'), ('FEA', 'Feature')], max_length=3)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
