# Generated by Django 4.2.4 on 2023-09-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_issue_assigned_to'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique project'),
        ),
    ]
