# Generated by Django 4.2.4 on 2023-09-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_project_unique_project'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique project',
        ),
    ]
